[project]
name = "clashless"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Marijan Beg", email = "m.beg@imperial.ac.uk" }
]
requires-python = ">=3.14"
dependencies = [
    "fakeitmakeit>=2025.10.1",
    "ortools>=9.15.6755",
    "pandas>=3.0.3",
]

[build-system]
requires = ["uv_build>=0.11.28,<0.12.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ipykernel>=7.3.0",
    "nbclient>=0.11.0",
    "pytest>=9.1.1",
    "pytest-cov>=7.1.0",
    "pytest-xdist>=3.8.0",
]
